#!/usr/bin/env bash
# docs-index.sh —— 索引 §8 全量清单的**生成/校验**工具（S12 §14 E3）
#
# 背景：`docs/README-导航与索引.md` §8 的「文档 | 状态 | 行数」表是**手工维护**的，
#   实测在两次修订内反复漂移（本轮实测 S12 602→607、篇数 58→59）。
#   凡「手工抄数字」必漂移——按 S12 §6.2 D4「数字单点化」纪律，该表应改为**生成物**。
#
# 真值来源（三条，均自动取得，无手抄）：
#   1. 篇数与顺序：`git ls-files -z 'docs/*.md'`（索引自身置顶，其余按路径排序）
#   2. `状态`：各篇状态头 `> **状态**：现行|历史|已失效`（与门禁 ① 同源）
#   3. `行数`：`wc -l` 实跑
#
# 用法:
#   bash scripts/docs-index.sh --verify   # 校验索引 §8 与实跑一致，不一致则红（进 gates）
#   bash scripts/docs-index.sh --write    # 用生成物**就地替换**索引 §8 表格（人只做搬运）
#   bash scripts/docs-index.sh --print    # 只打印生成物（供 diff 检视）
#
# 退出码: 0 = 一致 / 已写入；1 = --verify 发现漂移；2 = 用法错误
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

INDEX="docs/README-导航与索引.md"
START_RE='^## 8\. 全量文档清单'
END_RE='^</details>'

gen_table() {
  python3 - "$INDEX" <<'PYEOF'
import re, subprocess, sys, os
index = sys.argv[1]
files = [f.decode() for f in subprocess.run(
    ["git", "ls-files", "-z", "docs/*.md"], capture_output=True).stdout.split(b"\0") if f]
files = sorted(files)
# 清单**不含索引自身**（自指无检索价值），与旧表口径一致（58/59）
files = [f for f in files if f != index]
rows = []
for f in files:
    if not os.path.isfile(f):
        rows.append((f, "?", "MISSING", f))
        continue
    status = ""
    for line in open(f, encoding="utf-8"):
        if line.startswith("> **状态**："):
            m = re.match(r"^> \*\*状态\*\*：\s*(现行|历史|已失效)", line)
            status = m.group(1) if m else "非法"
            break
    n = sum(1 for _ in open(f, encoding="utf-8"))
    rel = os.path.relpath(f, "docs").replace(os.sep, "/")
    name = os.path.basename(f) if rel == os.path.basename(f) else rel
    rows.append((name, status, str(n), rel))
print("<!-- docs-index-table: generated by scripts/docs-index.sh; do not hand-edit -->")
print("| 文档 | 状态 | 行数 |")
print("|------|:----:|-----:|")
for name, status, n, rel in rows:
    print(f"| [{name}](./{rel}) | {status} | {n} |")
print(f"<!-- /docs-index-table -->")
print(f"<!-- docs-index-count: {len(rows)} -->")
PYEOF
}

extract_current() {
  python3 - "$INDEX" <<'PYEOF'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"<!-- docs-index-table: generated[^>]*-->.*?<!-- /docs-index-table -->(\n<!-- docs-index-count: \d+ -->)?", text, re.S)
if m:
    print(m.group(0)); raise SystemExit
# 回退：截取 §8 到 </details> 之间的表格
lines = text.split("\n")
start = next((i for i, l in enumerate(lines) if l.startswith("## 8. 全量文档清单")), None)
end = next((i for i, l in enumerate(lines) if l.startswith("</details>")), None)
if start is None or end is None:
    print(""); raise SystemExit
block = [l for l in lines[start:end] if l.startswith("| ") and "---" not in l]
print("\n".join(block))
PYEOF
}

mode="${1:-}"; [[ $# -eq 0 ]] && mode="--verify"
case "$mode" in
  --print) gen_table ;;
  --verify)
    cur="$(extract_current)"
    new="$(gen_table)"
    # 只比较「表格行 + 计数」的实质内容（忽略生成标记行，便于首次接入前的回退路径）
    norm() { grep -E '^\| |docs-index-count: ' <<<"$1" || true; }
    if [[ "$(norm "$cur")" == "$(norm "$new")" ]]; then
      cnt="$(grep -oE 'docs-index-count: [0-9]+' <<<"$new" | grep -oE '[0-9]+')"
      echo "  ✅ 索引 §8 与实跑一致（$cnt 篇）"
      exit 0
    fi
    echo "  ❌ 索引 §8 与实跑漂移。差异（< 索引现状 / > 应为）："
    diff <(norm "$cur") <(norm "$new") | sed 's/^/     /' || true
    echo "     处置：bash scripts/docs-index.sh --write  然后 git diff 检视"
    exit 1 ;;
  --write)
    new="$(gen_table)"
    python3 - "$INDEX" "$new" <<'PYEOF'
import re, sys
index, new = sys.argv[1], sys.argv[2]
text = open(index, encoding="utf-8").read()
pat = re.compile(r"<!-- docs-index-table: generated[^>]*-->.*?<!-- /docs-index-table -->(\n<!-- docs-index-count: \d+ -->)?", re.S)
if pat.search(text):
    text = pat.sub(lambda m: new.strip(), text, count=1)
else:
    # 首次接入：删掉 §8 → </details> 之间的**旧表格行**（含表头与分隔行），插入生成块
    lines = text.split("\n")
    s = next(i for i, l in enumerate(lines) if l.startswith("## 8. 全量文档清单"))
    e = next(i for i, l in enumerate(lines) if l.startswith("</details>"))
    kept = [l for l in lines[s:e] if not l.lstrip().startswith("|")]
    out = lines[:s] + kept + ["", new.strip(), ""] + lines[e:]
    text = "\n".join(out)
open(index, "w", encoding="utf-8").write(text)
print("  已写入生成块 ->", index)
PYEOF
    echo "  提示：本表交由生成器维护，请勿手工改行数（S12 §6.2 D4）。" ;;
  *) echo "用法: bash scripts/docs-index.sh [--verify|--write|--print]" >&2; exit 2 ;;
esac
